/* Published equipment ratings and transparent study assumptions, checked 2026-09-26. */
window.LAB_DATA = {
  panels: [
    {id:'jinko580',brand:'Jinko Solar',name:'Tiger Neo 580 W',model:'JKM580N-72HL4-V',watts:580,length:2.278,width:1.134,gamma:-0.0029,noct:45,price:70,priceStatus:'Planning allowance · quotation required',source:'https://www.jinkosolar.com/uploads/JKM570-590N-72HL4-%28V%29-F5-EN.pdf',supplier:'Almoayyed Solar, Ma’ameer · +973 1770 5275',supplierUrl:'https://almoayyedsolar.com/contact_us.html',availability:'Bahrain EPC inquiry route. Exact model and stock must be confirmed.'},
    {id:'longi570',brand:'LONGi',name:'Hi-MO 6 570 W',model:'LR5-72HTD-570M',watts:570,length:2.278,width:1.134,gamma:-0.0035,noct:45,price:65,priceStatus:'Planning allowance · quotation required',source:'https://static.longi.com/Hi_MO_6_Explorer_LR_5_72_HTD_550_570_M_V03_DG_a2bbc2e237.pdf',supplier:'Naif Falcon · regional supply to Bahrain from Dubai',supplierUrl:'https://www.naif-falcon.com/naif-falcon-bahrain/',availability:'Supplier lists LONGi brand for Bahrain. Exact model, shipping and availability unconfirmed.'}
  ],
  dx: [
    {id:'fral40',brand:'FRAL',name:'FSC40 spot cooler',model:'FSC40',cooling:13,power:3.4,flow:1700,price:1600,weight:135,phase:3,ambientLimit:null,source:'https://www.fral.it/en/catalogo/fsc40/',supplier:'Maven Trading · +973 3231 3062',supplierUrl:'https://www.maven-trading.bh/fral-portable-conditioner-in-bahrain.html',note:'13 kW is maximum published capacity; power quoted at 27°C / 60% RH. No high-ambient selection curve verified. IP22 standard, IP44 on request. Sheltered ground installation; exhaust remote from occupants.'},
    {id:'daikin60',brand:'Daikin',name:'5.2 TR packaged DX',model:'UATQ60C',cooling:18.32,power:4.52,flow:3398,price:2800,weight:350,phase:3,ambientLimit:52,source:'https://www.daikinindia.com/sites/default/files/Download%20Brochure/PA_10.pdf',supplier:'Almoayyed Contracting Group · Daikin Bahrain',supplierUrl:'https://www.daikinbahrain.com/en_us/contact.html',note:'Gross capacity rated at 27°C DB / 19°C WB entering air, 35°C outdoor; 380–415 V / 3 phase / 50 Hz. Operation to 52°C does not preserve rated capacity. Exact Bahrain model availability unconfirmed.'},
    {id:'daikin120',brand:'Daikin',name:'10.4 TR packaged DX',model:'UATQ120C',cooling:36.49,power:9.45,flow:7476,price:4900,weight:590,phase:3,ambientLimit:52,source:'https://www.daikinindia.com/sites/default/files/Download%20Brochure/PA_10.pdf',supplier:'Almoayyed Contracting Group · Daikin Bahrain',supplierUrl:'https://www.daikinbahrain.com/en_us/contact.html',note:'Gross rated capacity, same test conditions as UATQ60C. 380–415 V / 3 phase / 50 Hz. Heavy packaged machine on a separate pad with a duct to the pillar outlet; not hung on the pillar.'}
  ],
  inverters: [
    {id:'deye12',brand:'Deye',name:'12 kW hybrid',model:'SUN-12K-SG04LP3-EU',kw:12,eff:0.97,maxEff:0.976,maxPV:18,price:605,phase:3,source:'https://cn.deyeinverter.com/product/hybrid-inverter-1/sun8-10-12ksg01lp3.html',supplier:'MJS / deyeinverters.net · Dubai delivery to Bahrain',supplierUrl:'https://deyeinverters.net/en/wholesale/bahrain',priceStatus:'Advertised BHD reference · delivery / VAT not confirmed',note:'97% European efficiency used; 97.6% maximum. No battery is included in this study. Confirm strings, grid approval and manufacturer-approved parallel arrangement.'},
    {id:'growatt15',brand:'Growatt',name:'15 kW string',model:'MID 15KTL3-X',kw:15,eff:0.98,maxEff:0.9875,maxPV:22.5,price:600,phase:3,source:'https://en.growatt.com/products/mid-15-30ktl3-x-x2',supplier:'Naif Falcon · regional supply to Bahrain from Dubai',supplierUrl:'https://www.naif-falcon.com/naif-falcon-bahrain/',priceStatus:'Planning allowance · quotation required',note:'98% study conversion efficiency, below family maximum 98.75%. Grid connected; no off-grid or battery operation is modeled. Confirm exact model datasheet and string design.'}
  ],
  weather: [
    {id:'sep',name:'September · humid season',date:'2024-09-15',period:'September 2024',min:31.4,max:38.5,mean:34.4,rhMean:56,rhMin:35,rhMax:74,source:'https://wmo.int/media/news-from-members/monthly-weather-summary-september-2024'},
    {id:'jul',name:'July · peak summer',date:'2025-07-15',period:'July 2025',min:32.7,max:40.4,mean:36.1,rhMean:44,rhMin:24,rhMax:66,source:'https://public.wmo.int/sites/default/files/2025-08/MONTHLY%20WEATHER%20SUMMARY%20-JULY%202025.pdf'},
    {id:'jan',name:'January · mild season',date:'2025-01-15',period:'January 2025',min:15.1,max:20.7,mean:17.9,rhMean:63,rhMin:45,rhMax:79,source:'https://wmo.int/sites/default/files/2025-02/Read%20the%20full%20Monthly%20Weather%20Summary%20-%20January%202025.pdf'}
  ],
  sources: [
    ['Bahrain weather · September 2024','Bahrain Ministry of Transportation and Telecommunications, via WMO. Monthly mean daily extrema and RH; the hourly curves in this app are synthesized.','https://wmo.int/media/news-from-members/monthly-weather-summary-september-2024'],
    ['Bahrain weather · July 2025','Bahrain Meteorological Directorate; 32.7–40.4°C mean daily extrema, 44% mean RH.','https://public.wmo.int/sites/default/files/2025-08/MONTHLY%20WEATHER%20SUMMARY%20-JULY%202025.pdf'],
    ['Bahrain weather · January 2025','Bahrain Meteorological Directorate; 15.1–20.7°C mean daily extrema, 63% mean RH.','https://wmo.int/sites/default/files/2025-02/Read%20the%20full%20Monthly%20Weather%20Summary%20-%20January%202025.pdf'],
    ['EWA electricity tariffs','Commercial bands displayed by EWA: 22 fils/kWh up to 5,000 kWh/month, 32 fils thereafter. Use the actual site marginal tariff in Economics.','https://www.ewa.bh/en/tariff'],
    ['Jinko Solar module datasheet','Tiger Neo JKM570–590N-72HL4-(V), manufacturer reference. Confirm exact revision in quotation.','https://www.jinkosolar.com/uploads/JKM570-590N-72HL4-%28V%29-F5-EN.pdf'],
    ['LONGi module datasheet','Hi-MO 6 LR5-72HTD-550–570M; 2,278 × 1,134 mm, −0.35%/°C power coefficient.','https://static.longi.com/Hi_MO_6_Explorer_LR_5_72_HTD_550_570_M_V03_DG_a2bbc2e237.pdf'],
    ['FRAL FSC40','Manufacturer maximum cooling, electrical input and evaporator airflow. High ambient performance unverified.','https://www.fral.it/en/catalogo/fsc40/'],
    ['Daikin UATQ-C','Manufacturer rating table on page 21 (PDF page index 20). Ratings are not 100% outdoor-air selections.','https://www.daikinindia.com/sites/default/files/Download%20Brochure/PA_10.pdf'],
    ['Deye inverter','Manufacturer family specifications; verify installed unit revision and phase current limits.','https://cn.deyeinverter.com/product/hybrid-inverter-1/sun8-10-12ksg01lp3.html'],
    ['Growatt inverter','MID 15–30KTL3-X/X2 family manufacturer page; 98.75% maximum efficiency.','https://en.growatt.com/products/mid-15-30ktl3-x-x2'],
    ['Bahrain solar installation','Almoayyed Solar, Ma’ameer: +973 1770 5275. Supplier inquiry, not a model-specific quotation.','https://almoayyedsolar.com/contact_us.html'],
    ['Bahrain manufactured PV option','Solar One, Askar: +973 1776 5271. Request a current module sheet to add to the catalog.','https://solarone.me/contact'],
    ['Regional module / inverter supply','Naif Falcon serves Bahrain from Dubai; LONGi, Jinko, Growatt and Deye listed.','https://www.naif-falcon.com/naif-falcon-bahrain/'],
    ['Advertised inverter price reference','Regional reseller lists SUN-12K-SG04LP3-EU at BHD 605. Treat as an indicative equipment price; reconfirm landed price and taxes.','https://deyeinverters.net/en/wholesale/bahrain'],
    ['Bahrain DX supply','Maven lists FRAL portable air conditioning; exact unit, availability and price require quotation.','https://www.maven-trading.bh/fral-portable-conditioner-in-bahrain.html'],
    ['Daikin Bahrain','Local distributor inquiry through the Bahrain sales network.','https://www.daikinbahrain.com/en_us/contact.html'],
    ['Solar position reference','NOAA fractional-year solar declination and equation of time; approximate geometry at 26.257°N, 50.611°E, UTC+3.','https://gml.noaa.gov/grad/solcalc/calcdetails.html'],
    ['PV calculation reference','NREL PVWatts technical reference. This app uses a simpler NOCT temperature model; it does not run PVWatts or use measured irradiance.','https://pvwatts.nrel.gov/downloads/pvwattsv5.pdf'],
    ['DX coil modeling reference','EnergyPlus engineering reference describes apparatus dew point / bypass-factor models. This app uses a simplified capacity-limited moist-air balance, not EnergyPlus.','https://energyplus.net/assets/nrel_custom/pdfs/pdfs_v24.2.0/EngineeringReference.pdf']
  ]
};
