(function(){
  'use strict';
  const E=window.LabEngine,D=window.LAB_DATA,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
  let state={...E.defaults},geo,result,field,day,cost,dayKey='',layoutKey='',timer=null,queued=null;
  const fmt=(v,n=1)=>Number.isFinite(v)?v.toLocaleString('en-GB',{minimumFractionDigits:n,maximumFractionDigits:n}):'—';
  const money=v=>fmt(v,0),clock=t=>{const m=Math.round(t*60)%1440;return `${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`;};
  const range=(key,label,min,max,step,unit='',note='')=>`<div class="field"><div class="field-head"><label for="control-${key}">${label}</label><output data-output="${key}" data-unit="${unit}">${state[key]} ${unit}</output></div><div class="range-row"><input id="control-${key}" data-key="${key}" type="range" min="${min}" max="${max}" step="${step}" value="${state[key]}"><input data-key="${key}" aria-label="${label}, numeric value" type="number" min="${min}" max="${max}" step="${step}" value="${state[key]}"></div>${note?`<small>${note}</small>`:''}</div>`;
  const num=(key,label,min,max,step,unit='',note='')=>`<div class="field"><div class="field-head"><label for="number-${key}">${label}</label><span class="caption">${unit}</span></div><input id="number-${key}" data-key="${key}" type="number" min="${min}" max="${max}" step="${step}" value="${state[key]}">${note?`<small>${note}</small>`:''}</div>`;
  const select=(key,label,options)=>`<div class="field"><div class="field-head"><label for="select-${key}">${label}</label></div><select id="select-${key}" data-key="${key}">${options.map(o=>`<option value="${o[0]}"${state[key]===o[0]?' selected':''}>${o[1]}</option>`).join('')}</select></div>`;
  const toggle=(key,label,note='')=>`<label class="toggle-row"><span>${label}</span><input type="checkbox" data-key="${key}" ${state[key]?'checked':''}></label>${note?`<p class="caption">${note}</p>`:''}`;
  const row=(label,value,total=false)=>`<div class="metric-row${total?' total':''}"><span>${label}</span><strong>${value}</strong></div>`;
  const specRow=(label,value)=>`<div class="spec-row"><span>${label}</span><b>${value}</b></div>`;
  const kpi=(label,value,unit,note,tone='')=>`<div class="kpi ${tone}"><small>${label}</small><strong>${value}<em>${unit}</em></strong><p>${note}</p></div>`;
  const mini=(label,value,unit)=>`<div><small>${label}</small><b>${value} <em>${unit}</em></b></div>`;
  const link=(url,text)=>`<a href="${url}" target="_blank" rel="noopener noreferrer">${text} ↗</a>`;
  const scene=new ParkScene($('#scene'),selectSystem,p=>{const el=$('#probe');if(!p){el.hidden=true;return;}el.innerHTML=`<b>${fmt(p.temp)}°C</b><br>${fmt(p.rh,0)}% RH · air estimate<br>x ${fmt(p.x)} m · y ${fmt(p.y)} m`;el.hidden=false;el.style.left=Math.min(p.px+15,$('#scene-wrap').clientWidth-165)+'px';el.style.top=Math.max(50,Math.min(p.py-60,$('#scene-wrap').clientHeight-90))+'px';});
  function selectSystem(name){state.selected=name;renderInspector();scene.needs=true;if(window.innerWidth<900)document.querySelector('.inspector').scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'nearest'});}
  function renderInspector(){const kind=state.selected,names={solar:['SYSTEM 01','Solar canopy'],dx:['SYSTEM 02','DX cooling'],inverter:['SYSTEM 03','Power conversion'],site:['SITE GEOMETRY','Calisthenics zone'],weather:['BOUNDARY CONDITIONS','Bahrain weather']};
    $('#inspector-eyebrow').textContent=names[kind][0];$('#inspector-title').textContent=names[kind][1];$$('[data-select]').forEach(b=>b.classList.toggle('active',b.dataset.select===kind));
    let html='';
    if(kind==='solar')html=select('panelId','Module model',D.panels.map(x=>[x.id,x.name]))+'<div id="equipment-spec" class="spec-card"></div>'+range('panelCount','Requested modules',0,150,1,'units')+range('strips','Canopy strips',1,8,1)+range('height','Canopy height',2.8,7,.1,'m')+range('tilt','Panel tilt',0,30,1,'°')+'<div id="inspector-totals" class="mini-total"></div><div id="equipment-note" class="info-box"></div>'+num('panelPrice','Module unit price',0,2000,1,'BHD')+'<details><summary>Losses & placement</summary>'+range('soiling','Soiling loss',0,40,1,'%')+'<p class="caption">Modules fit inside the schematic footprint. Requested modules that cannot fit are excluded from energy and costs. Lower canopies avoid tree-crown collisions. Fixed 0.10 m gaps along each strip; strips are distributed across the site.</p></details><div id="equipment-supplier" class="supplier"></div>';
    if(kind==='dx')html=select('dxId','Cooling equipment',D.dx.map(x=>[x.id,x.name]))+'<div id="equipment-spec" class="spec-card"></div>'+range('dxCount','Installed DX units',0,12,1,'units')+'<div id="inspector-totals" class="mini-total"></div>'+num('dxPrice','Equipment unit price',0,50000,50,'BHD')+'<div id="equipment-note" class="info-box"></div><details><summary>Coil & airflow assumptions</summary>'+range('adp','Apparatus dew point',5,20,.5,'°C')+range('bypass','Minimum bypass fraction',.05,.5,.01)+range('derate','Capacity loss above 35°C',0,3,.1,'% / °C')+range('powerRise','Power rise above 35°C',0,3,.1,'% / °C')+range('outletArea','Outlet area per DX unit',.05,.7,.01,'m²')+range('mix','Turbulent diffusivity',.05,1.5,.05,'m²/s')+range('mixHeight','Occupied mixing layer',1,4,.1,'m')+'<p class="caption">Corrections are study assumptions. The condenser exhaust is outside the modeled zone. Outlet geometry, static pressure and duct losses need supplier selection.</p></details><div id="equipment-supplier" class="supplier"></div>';
    if(kind==='inverter')html=select('inverterId','Inverter model',D.inverters.map(x=>[x.id,x.brand+' '+x.name]))+'<div id="equipment-spec" class="spec-card"></div>'+range('inverterCount','Parallel / distributed units',0,8,1,'units')+'<div id="inspector-totals" class="mini-total"></div>'+toggle('solarOnly','Stage DX to available solar','Both modes assume a connected grid reference. Off-grid stability and compressor startup are outside this study.')+num('inverterPrice','Inverter unit price',0,20000,5,'BHD')+'<div id="equipment-note" class="info-box"></div><details><summary>Current calculations</summary>'+num('dcVoltage','Equivalent DC operating voltage',200,800,10,'V')+range('pf','DX power factor',.7,1,.01)+'<p class="caption">Three-phase AC at 400 V. Current follows power and voltage; it is not an independent energy setting. DC current is an equivalent aggregate, not a PV string or cable design.</p></details><div id="equipment-supplier" class="supplier"></div>';
    if(kind==='site')html='<div class="info-box amber">Schematic reconstruction from your sketch. Bearings and north were not supplied. The calculated area is provisional.</div>'+range('width','Overall width',15,60,.1,'m')+range('depth','Overall depth',10,40,.1,'m')+range('heading','Site rotation from east',0,355,5,'°')+range('treeHeight','Tree height',2,7,.1,'m')+range('trees','Existing trees',0,8,1,'trees')+'<div id="inspector-totals" class="mini-total"></div><p class="caption">Six calisthenics stations are fixed illustrative objects. Tree count and placement are assumptions; only the approximate 4 m height was supplied. Changing dimensions rescales the outline and refits the canopy.</p><div class="supplier">'+link('assets/site-sketch.png','Open your original sketch')+'</div>';
    if(kind==='weather')html=select('profile','Bahrain reference period',D.weather.map(x=>[x.id,x.name]))+'<div id="equipment-spec" class="spec-card"></div>'+toggle('manual','Use manual temperature & RH')+range('temp','Air temperature',10,52,.1,'°C')+range('rh','Relative humidity',5,95,1,'%')+range('wind','Wind at occupant height',0,8,.1,'m/s')+range('windDir','Wind coming from',0,355,5,'° N')+range('sky','Atmospheric solar factor',.15,1,.01)+'<div id="equipment-note" class="info-box"></div><p class="caption">Changing the period also changes the sun geometry date. The hourly profiles are generated from monthly summaries; they are not measured hourly weather. The solar factor is an assumption.</p>';
    $('#inspector-content').innerHTML=html;refreshInspector();syncControls();}
  function refreshInspector(){if(!result||!$('#inspector-content').hasChildNodes())return;const s=state,g=geo,r=result,kind=s.selected,el=$('#equipment-spec'),tot=$('#inspector-totals'),note=$('#equipment-note'),sup=$('#equipment-supplier');
    if(kind==='solar'){el.innerHTML=`<span class="spec-brand">${g.panel.brand}</span><div class="spec-model">${g.panel.model}</div>`+specRow('Nameplate / module',g.panel.watts+' Wp')+specRow('DC output now / module',fmt(g.panels.length?r.pv.dc*1000/g.panels.length:0,0)+' W')+specRow('Module dimensions','2.278 × 1.134 m')+specRow('Fitted / requested',`${g.panels.length} / ${s.panelCount}`);
      tot.innerHTML=mini('Solar AC now',fmt(r.pv.ac,2),'kW')+mini('PV ground shadow',fmt(r.shade.pv*100,0),'%')+mini('Installed array',fmt(r.pv.nameplate,2),'kWp')+mini('Shaded footprint',fmt(r.shade.pv*g.area,0),'m²');
      note.innerHTML=`${g.panels.length<s.panelCount?`Only ${g.panels.length} modules fit. Increase strips or area, or reduce the request. `:''}PV + tree shade: <b>${fmt(r.shade.union*100,0)}%</b>. Shortwave MRT reduction in shade: <b>${fmt(r.mrtDrop)}°C</b>. This is radiant exposure, not an air-temperature drop.`;
      sup.innerHTML=g.panel.priceStatus+'<br>'+link(g.panel.source,'Manufacturer datasheet')+'<br>'+link(g.panel.supplierUrl,g.panel.supplier)+'<br>'+g.panel.availability;}
    if(kind==='dx'){el.innerHTML=`<span class="spec-brand">${g.dx.brand}</span><div class="spec-model">${g.dx.model}</div>`+specRow('Rated total cooling',fmt(g.dx.cooling,2)+' kW')+specRow('Rated electricity',fmt(g.dx.power,2)+' kW')+specRow('Supply air / unit',fmt(g.dx.flow,0)+' m³/h')+specRow('Estimated supply now',fmt(r.coil.tout)+'°C / '+fmt(r.coil.rhout,0)+'% RH')+specRow('Across-coil drop',fmt(r.coil.delta)+'°C')+specRow('Condensate / active unit',fmt(r.coil.water,2)+' L/h');
      tot.innerHTML=mini('Active / installed',`${r.active} / ${s.dxCount}`,'units')+mini('Total electricity',fmt(r.load,2),'kW')+mini('Occupied-area mean drop',fmt(field.meanDrop,2),'°C')+mini('Total air delivered',fmt(r.totalFlow,0),'m³/h');
      note.innerHTML=`${r.active===0?'DX is currently off: check the schedule, ambient temperature or solar-following control. ':''}Adding units increases cooling capacity and coverage; temperature drops do not add. ${g.dx.note}`;sup.innerHTML='Price is a planning allowance, not a supplier quote.<br>'+link(g.dx.source,'Published specifications')+'<br>'+link(g.dx.supplierUrl,g.dx.supplier);}
    if(kind==='inverter'){el.innerHTML=`<span class="spec-brand">${g.inverter.brand}</span><div class="spec-model">${g.inverter.model}</div>`+specRow('AC rating / unit',g.inverter.kw+' kW')+specRow('Conversion efficiency used',fmt(g.inverter.eff*100,1)+'%')+specRow('AC current now / unit',fmt(s.inverterCount?r.pv.ac*1000/(Math.sqrt(3)*400*s.inverterCount):0,1)+' A / phase')+specRow('Rated current / unit',fmt(g.inverter.kw*1000/(Math.sqrt(3)*400),1)+' A / phase')+specRow('Equivalent total DC',fmt(r.pv.dc*1000/s.dcVoltage,1)+' A');
      tot.innerHTML=mini('Total AC rating',fmt(r.pv.maxAC,0),'kW')+mini('Grid import now',fmt(r.grid,2),'kW')+mini('Conversion loss',fmt(r.pv.loss,2),'kW')+mini('Clipped solar',fmt(r.pv.clipping,2),'kW');
      note.innerHTML=`${r.pv.nameplate>s.inverterCount*g.inverter.maxPV?'Array nameplate exceeds the catalog DC sizing allowance. Verify the inverter selection. ':''}${s.inverterCount===0?'Without an inverter no PV electricity reaches the DX AC supply. ':''}${g.inverter.note}`;sup.innerHTML=g.inverter.priceStatus+'<br>'+link(g.inverter.source,'Manufacturer specifications')+'<br>'+link(g.inverter.supplierUrl,g.inverter.supplier);}
    if(kind==='site')tot.innerHTML=mini('Provisional footprint',fmt(g.area,1),'m²')+mini('Exercise stations','6','stations')+mini('Canopy pillars',g.posts.length,'bases')+mini('Tree shade now',fmt(r.shade.tree*100,0),'%');
    if(kind==='weather'){const w=r.w.profile;el.innerHTML=`<span class="spec-brand">Bahrain Meteorological Directorate</span><div class="spec-model">${w.period}</div>`+specRow('Mean daily low / high',w.min+' / '+w.max+'°C')+specRow('Mean monthly RH',w.rhMean+'%')+specRow('Mean RH low / high',w.rhMin+' / '+w.rhMax+'%')+`<div class="supplier">${link(w.source,'Original local report')}</div>`;
      note.innerHTML=`${s.manual?'Manual override is active.':'Automatic representative profile is active.'} Now <b>${fmt(r.w.temp)}°C, ${fmt(r.w.rh,0)}% RH</b>. Dew point <b>${fmt(E.dewpoint(r.w.temp,r.w.rh))}°C</b>. Sunset approximately ${clock(r.sun.sunset)}.`;
      $$('[data-key="temp"], [data-key="rh"]').forEach(i=>{i.disabled=!s.manual;i.closest('.field').style.opacity=s.manual?'1':'.5';});}}
  function syncControls(){for(const el of $$('[data-key]')){const key=el.dataset.key;if(el===document.activeElement)continue;if(el.type==='checkbox')el.checked=state[key];else el.value=state[key];}for(const o of $$('[data-output]')){const v=state[o.dataset.output];o.textContent=(Number.isInteger(v)?v:Number(v.toFixed(2)))+' '+o.dataset.unit;}$('#time').value=state.time;$('#showCanopy').checked=state.showCanopy;}
  function setValue(key,value,element){if(typeof state[key]==='number'){if(!Number.isFinite(value))return;if(element){const min=parseFloat(element.min),max=parseFloat(element.max);if(Number.isFinite(min))value=Math.max(min,value);if(Number.isFinite(max))value=Math.min(max,value);}if(['panelCount','strips','dxCount','inverterCount','trees','days','visits','years'].includes(key))value=Math.round(value);}state[key]=value;
    if(key==='panelId')state.panelPrice=D.panels.find(p=>p.id===value).price;if(key==='dxId')state.dxPrice=D.dx.find(p=>p.id===value).price;if(key==='inverterId')state.inverterPrice=D.inverters.find(p=>p.id===value).price;
    syncControls();if(queued)clearTimeout(queued);queued=setTimeout(calculate,key==='time'?0:40);}
  document.addEventListener('input',e=>{const el=e.target;if(el.dataset.key){const val=el.type==='checkbox'?el.checked:el.tagName==='SELECT'?el.value:el.value===''?NaN:Number(el.value);setValue(el.dataset.key,val,el);}});
  document.addEventListener('change',e=>{if(e.target.dataset.key&&e.target.value===''){e.target.value=state[e.target.dataset.key];}});
  function calculate(){queued=null;const s=state,lk=JSON.stringify([s.width,s.depth,s.trees,s.treeHeight,s.strips,s.height,s.tilt,s.panelId,s.panelCount,s.dxId,s.dxCount,s.inverterId,s.inverterCount]);
    if(lk!==layoutKey){geo=E.layout(s);layoutKey=lk;}
    result=E.instant(s,geo);field=E.transport(s,geo,result);
    const ignore=['time','selected','layer','view','playing','showFlows','showCanopy'];const dk=JSON.stringify(Object.fromEntries(Object.entries(s).filter(([k])=>!ignore.includes(k))));
    if(dk!==dayKey){day=E.daily(s,geo);cost=E.economics(s,geo,day);dayKey=dk;renderEconomics();renderDaily();}
    renderLive();refreshInspector();scene.update(s,geo,result,field);window.lab={state,geo,result,field,day,cost,calculate};}
  function renderLive(){const s=state,g=geo,r=result;
    $('#clock-time').textContent=clock(s.time);$('#sun-angle').textContent=fmt(r.sun.elevation,1)+'°';$('#weather-summary').textContent=`${fmt(r.w.temp)}°C · ${fmt(r.w.rh,0)}%`;$('#weather-symbol').textContent=r.sun.elevation>0?'☀':'☾';
    $('#area-label').textContent=fmt(g.area,0)+' m² · schematic';$('#scene-mode').textContent=s.layer==='temperature'?'AIR TEMPERATURE · REDUCED-ORDER MODEL':s.layer==='radiant'?'SHORTWAVE RADIANT EXPOSURE':'SOLAR CANOPY STUDY';
    $('#studio-kpis').innerHTML=kpi('Solar electricity now',fmt(r.pv.ac,2),'kW AC',fmt(r.pv.nameplate,2)+' kWp installed','mint')+kpi('Total shadow coverage',fmt(r.shade.union*100,0),'%',fmt(r.shade.union*g.area,0)+' m² · PV + trees','blue')+kpi('Area mean DX air drop',fmt(field.meanDrop,2),'°C','Mixing-layer estimate · not supply air','blue')+kpi('Condensate collected',fmt(r.water,1),'L/h',r.active+' active units','amber');
    $('#study-note').textContent=`Provisional ${fmt(g.area,1)} m² footprint. ${state.manual?'Manual weather.':'Weather curves based on Bahrain monthly reports.'} ${r.active?`${fmt(field.cooledArea,0)} m² modeled at ≥1°C air reduction.`:'DX is off at this time.'}`;
    const legend=$('#legend');legend.hidden=s.layer==='scene';$('#legend-min').textContent=fmt(s.layer==='radiant'?r.mrtShade:r.w.temp-Math.max(1,field.maxDrop))+'°C';$('#legend-max').textContent=fmt(s.layer==='radiant'?Math.max(r.mrtShade+1,r.mrtSun):r.w.temp)+'°C';
    $('#energy-flow').innerHTML=`<div class="flow-node"><i>▦</i><b>${fmt(r.pv.dc,1)} kW</b><small>PV · DC</small></div><span class="flow-link">→</span><div class="flow-node"><i>ϟ</i><b>${fmt(r.pv.ac,1)} kW</b><small>Inverter · AC</small></div><span class="flow-link">→</span><div class="flow-node"><i style="color:var(--blue)">❄</i><b>${fmt(r.load,1)} kW</b><small>DX demand</small></div><div class="flow-node"><i style="color:var(--blue)">⌁</i><b>${fmt(r.grid,1)} kW</b><small>Grid import</small></div>`;
    $('#distance-chart').innerHTML=lineChart([{name:'Air temperature',values:field.profile.map(p=>[p.d,p.temp]),color:'#78dfe8'}],{xMax:12,yMin:Math.floor(r.w.temp-Math.max(1,field.maxDrop)),yMax:Math.ceil(r.w.temp),height:150,yUnit:'°C',xUnit:'m',xTicks:[0,3,6,9,12]});
    $('#performance-kpis').innerHTML=kpi('DX total cooling now',fmt(r.totalQ,1),'kW',fmt(r.totalSensible,1)+' kW sensible','blue')+kpi('Supply air / active unit',fmt(r.coil.tout,1),'°C',fmt(r.coil.delta,1)+'°C across-coil drop','mint')+kpi('Solar share of load now',r.load?fmt(r.self/r.load*100,0):'—','%',r.load?'Simultaneous PV use':'No active DX demand','mint')+kpi('Cooling COP / active unit',fmt(r.coil.cop,2),'W/W','Estimated off-design efficiency','amber');
    $('#coil-calculation').innerHTML=row('Ambient / dew point',fmt(r.w.temp)+' / '+fmt(E.dewpoint(r.w.temp,r.w.rh))+'°C')+row('Inlet humidity ratio',fmt(r.coil.win*1000,2)+' g/kg dry air')+row('Outlet humidity ratio',fmt(r.coil.wout*1000,2)+' g/kg dry air')+row('Dry air mass flow / unit',fmt(r.coil.mdry,3)+' kg/s')+row('Enthalpy change',fmt(r.coil.hin,2)+' − '+fmt(r.coil.hout,2)+' kJ/kg')+row('Coil cooling / unit',fmt(r.coil.mdry,3)+' × '+fmt(r.coil.hin-r.coil.hout,2)+' = '+fmt(r.coil.q,2)+' kW')+row('Condensate / unit',fmt(r.coil.water,2)+' L/h')+row('Total recovered water',fmt(r.coil.water,2)+' × '+r.active+' = '+fmt(r.water,2)+' L/h',true)+row('DX line current · 400 V, 3φ',fmt(r.load*1000/(Math.sqrt(3)*400*s.pf),1)+' A/phase')+row('Remote condenser heat rejection',fmt(r.totalQ+r.load,2)+' kW');
    $('#transport-stats').innerHTML=mini('Finite-volume grid',field.nx+' × '+field.ny,'cells')+mini('Cell spacing',fmt(field.dx,2)+' × '+fmt(field.dy,2),'m')+mini('Solver sweeps',field.iterations,'iterations')+mini('Last fraction update',field.residual.toExponential(1),'');
  }
  function renderDaily(){const d=day,s=state;$('#profile-label').textContent=result.w.profile.period+(s.manual?' · manual override':' · representative day');
    $('#power-chart').innerHTML=lineChart([{name:'Solar AC',color:'#65e0c3',values:d.rows.map(r=>[r.t,r.pv.ac])},{name:'DX load',color:'#ffc77b',values:d.rows.map(r=>[r.t,r.load])}],{xMax:24,yMax:Math.max(1,...d.rows.map(r=>Math.max(r.pv.ac,r.load)))*1.1,yMin:0,yUnit:'kW',xTicks:[0,6,12,18,24],xUnit:'h'});
    $('#water-chart').innerHTML=lineChart([{name:'Condensate',color:'#6db9ff',values:d.rows.map(r=>[r.t,r.water])}],{xMax:24,yMax:Math.max(1,...d.rows.map(r=>r.water))*1.1,yMin:0,yUnit:'L/h',xTicks:[0,6,12,18,24],xUnit:'h'});
    $('#daily-balance').innerHTML=row('Daily solar AC generation',fmt(d.pv,1)+' kWh')+row('Daily DX electricity demand',fmt(d.load,1)+' kWh')+row('Directly used solar',fmt(d.self,1)+' kWh')+row('Grid import',fmt(d.grid,1)+' kWh')+row('PV surplus / curtailed',fmt(d.surplus,1)+' kWh')+row('Recovered condensate',fmt(d.water,1)+' L/day',true)+row('Nominal tank for one study day',Math.ceil(d.water*1.2/10)*10+' L including 20% margin');}
  function renderEconomics(){const focusedKey=document.activeElement?.classList.contains('money-input')?document.activeElement.dataset.key:null;const c=cost,s=state;$('#cost-kpis').innerHTML=kpi('Capital cost',money(c.capex),'BHD','Including allowances, contingency & tax','mint')+kpi('Annual operating cost',money(c.opex),'BHD/year','Selected day × '+s.days+' days','amber')+kpi('First-year total',money(c.year1),'BHD','CAPEX + year-one OPEX')+kpi(s.years+'-year total',money(c.lifetime),'BHD','Undiscounted · with inverter renewal','blue');
    const keys=['panelPrice',null,'footingRate','dxPrice','inverterPrice','pvLabor','dxLabor','inverterLabor','wiringRate','drainRate','design','shipping'];
    $('#capex-table').innerHTML='<table><thead><tr><th>Item</th><th>Quantity</th><th>Rate · BHD</th><th>Total · BHD</th></tr></thead><tbody>'+c.lines.map((l,i)=>`<tr><td>${l.label}<small>${l.unit}</small></td><td>${fmt(l.qty,l.qty%1?2:0)}</td><td>${keys[i]?`<input class="money-input" data-key="${keys[i]}" type="number" min="0" max="100000" step="1" aria-label="${l.label} rate" value="${s[keys[i]]}">`:fmt(l.rate,2)}</td><td>${fmt(l.total,2)}</td></tr>`).join('')+`<tr><td colspan="3">Subtotal</td><td>${fmt(c.subtotal,2)}</td></tr><tr><td colspan="3">Contingency · ${s.contingency}%</td><td>${fmt(c.contingency,2)}</td></tr><tr><td colspan="3">Tax allowance · ${s.tax}%</td><td>${fmt(c.tax,2)}</td></tr><tr class="total"><td colspan="3">Total CAPEX</td><td>${fmt(c.capex,2)}</td></tr></tbody></table>`;
    $('#opex-table').innerHTML='<table><thead><tr><th>Item</th><th>Annual quantity</th><th>Rate · BHD</th><th>Annual · BHD</th></tr></thead><tbody>'+c.op.map(l=>`<tr><td>${l.label}<small>${l.unit}</small></td><td>${fmt(l.qty,l.qty%1?1:0)}</td><td>${fmt(l.rate,3)}</td><td>${fmt(l.total,2)}</td></tr>`).join('')+`<tr class="total"><td colspan="3">Total annual OPEX</td><td>${fmt(c.opex,2)}</td></tr></tbody></table>`;
    $('#lifecycle').innerHTML=row('First year',fmt(c.capex,2)+' + '+fmt(c.opex,2)+' = '+fmt(c.year1,2)+' BHD')+row(s.years+'-year undiscounted cost',fmt(c.capex,2)+' + '+s.years+' × '+fmt(c.opex,2)+' + '+fmt(c.replacement,2)+' = '+fmt(c.lifetime,2)+' BHD')+row('Net present cost · '+s.discount+'% real discount',fmt(c.npv,2)+' BHD',true)+row('Annual avoided grid purchase from PV',fmt(c.avoided,2)+' BHD/year')+'<p class="caption">Avoided electricity is a gross saving relative to the same actual DX consumption supplied by the grid. It excludes the incremental capital and maintenance costs of the solar system; it is not profit.</p>';if(focusedKey){const replacement=document.querySelector('#capex-table [data-key="'+focusedKey+'"]');if(replacement)replacement.focus({preventScroll:true});}}
  function lineChart(series,o){const width=580,height=o.height||250,left=47,right=18,top=20,bottom=30,W=width-left-right,H=height-top-bottom,yMax=o.yMax,yMin=o.yMin,range=Math.max(.1,yMax-yMin),X=v=>left+v/o.xMax*W,Y=v=>top+(1-(v-yMin)/range)*H;
    let svg=`<svg viewBox="0 0 ${width} ${height}" role="img" aria-label="${series.map(x=>x.name).join(' and ')} chart"><title>${series.map(x=>x.name).join(' and ')}; ${o.yUnit} versus ${o.xUnit}</title>`;
    for(let i=0;i<4;i++){const val=yMin+range*i/3,y=Y(val);svg+=`<line x1="${left}" y1="${y}" x2="${width-right}" y2="${y}" stroke="#385060" stroke-width=".6"/><text x="${left-8}" y="${y+4}" text-anchor="end">${fmt(val,range<4?1:0)}</text>`;}
    svg+=`<text x="${left}" y="11">${o.yUnit}</text>`;for(const t of o.xTicks)svg+=`<text x="${X(t)}" y="${height-7}" text-anchor="middle">${t}${t===o.xMax?' '+o.xUnit:''}</text>`;
    for(const ser of series){const path=ser.values.map((v,i)=>(i?'L':'M')+X(v[0]).toFixed(2)+','+Y(v[1]).toFixed(2)).join(' ');if(series.length===1)svg+=`<path d="${path} L${X(ser.values.at(-1)[0])},${Y(yMin)} L${X(ser.values[0][0])},${Y(yMin)} Z" fill="${ser.color}" opacity=".07"/>`;svg+=`<path d="${path}" fill="none" stroke="${ser.color}" stroke-width="2" stroke-linejoin="round"/>`;}
    return svg+'</svg>';}
  function showTab(name){$$('.tab-content').forEach(x=>x.classList.toggle('active',x.id===name));$$('[data-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.tab===name);b.setAttribute('aria-selected',b.dataset.tab===name);});if(name==='simulation')scene.needs=true;else window.scrollTo({top:0,behavior:'smooth'});}
  document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.select)selectSystem(b.dataset.select);if(b.dataset.tab)showTab(b.dataset.tab);if(b.dataset.goto)showTab(b.dataset.goto);if(b.dataset.layer){state.layer=b.dataset.layer;$$('[data-layer]').forEach(x=>x.classList.toggle('active',x.dataset.layer===state.layer));renderLive();scene.needs=true;}});
  $('#time').addEventListener('input',e=>setValue('time',+e.target.value));$('#showCanopy').addEventListener('change',e=>{state.showCanopy=e.target.checked;scene.needs=true;});$('#weather-open').addEventListener('click',()=>selectSystem('weather'));
  $('#view-iso').addEventListener('click',()=>setView('iso'));$('#view-plan').addEventListener('click',()=>setView('plan'));
  function setView(v){state.view=v;$('#view-iso').classList.toggle('active',v==='iso');$('#view-plan').classList.toggle('active',v==='plan');$('#scene-hint').textContent=v==='plan'?'Hover / tap to probe · select equipment to edit':'Drag to orbit · select an object to edit';scene.needs=true;}
  $('#zoom-in').addEventListener('click',()=>{scene.zoom=E.clamp(scene.zoom+.1,.65,1.6);scene.needs=true;});$('#zoom-out').addEventListener('click',()=>{scene.zoom=E.clamp(scene.zoom-.1,.65,1.6);scene.needs=true;});
  function stop(){clearInterval(timer);timer=null;state.playing=false;$('#play').textContent='▶';$('#play').setAttribute('aria-label','Animate the day');}
  $('#play').addEventListener('click',()=>{if(timer){stop();return;}state.playing=true;$('#play').textContent='Ⅱ';$('#play').setAttribute('aria-label','Pause the day');timer=setInterval(()=>{state.time=(state.time+.125)%24;syncControls();calculate();},180);});
  $('#reset').addEventListener('click',()=>{stop();state={...E.defaults};dayKey='';layoutKey='';scene.yaw=-.42;scene.zoom=1;setView('iso');$$('[data-layer]').forEach(x=>x.classList.toggle('active',x.dataset.layer==='scene'));calculate();renderInspector();syncControls();toast('Initial study restored.');});
  function toast(text){const el=$('#toast');el.textContent=text;el.hidden=false;setTimeout(()=>el.hidden=true,3500);}
  $('#export').addEventListener('click',()=>{const rows=[['Muharraq Climate Lab','Concept estimate, not validated CFD'],['Weather',result.w.profile.period+(state.manual?' manual override':' representative day')],['Time (Bahrain)',clock(state.time)],['Footprint (m2), provisional',geo.area],['Solar AC now (kW)',result.pv.ac],['DX electrical load now (kW)',result.load],['Coil supply temperature (C)',result.coil.tout],['Occupied area mean air drop (C)',field.meanDrop],['PV shadow fraction',result.shade.pv],['Condensate now (L/h)',result.water],['Daily solar (kWh)',day.pv],['Daily load (kWh)',day.load],['Daily grid (kWh)',day.grid],['Daily condensate (L)',day.water],[],['CAPEX item','Quantity','Rate BHD','Total BHD']];
    cost.lines.forEach(l=>rows.push([l.label,l.qty,l.rate,l.total]));rows.push(['Contingency','','',cost.contingency],['Tax allowance','','',cost.tax],['Total CAPEX','','',cost.capex],[],['OPEX item','Annual quantity','Rate BHD','Annual total BHD']);cost.op.forEach(l=>rows.push([l.label,l.qty,l.rate,l.total]));rows.push(['Annual OPEX','','',cost.opex],['First year total','','',cost.year1],['Lifetime undiscounted','','',cost.lifetime],['Net present cost','','',cost.npv],[],['INPUTS','Value']);Object.entries(state).forEach(([k,v])=>rows.push([k,v]));rows.push([],['SOURCES','URL']);D.sources.forEach(x=>rows.push([x[0],x[2]]));
    const csv='\uFEFF'+rows.map(row=>row.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='Muharraq_Cooling_Study.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Calculation report exported as CSV.');});
  $('#schedule-controls').innerHTML=num('start','DX starts at',0,23,.5,'hour')+num('end','DX stops at',0,24,.5,'hour')+toggle('solarOnly','Stage DX to available solar','No batteries. If off, the grid supplies any shortfall.');
  $('#cost-controls').innerHTML=num('days','Operating days per year',1,365,1,'days')+num('tariff','Marginal electricity tariff',0,.2,.001,'BHD/kWh','EWA commercial: 0.022 first band / 0.032 upper band. Select the site’s actual marginal rate.')+num('exportTariff','Export credit assumption',0,.1,.001,'BHD/kWh','Default zero; no unverified net-billing revenue.')+num('steelRate','Canopy steel at 4.5 m',0,300,1,'BHD/m²','Scaled by (height / 4.5)^1.35; budget sensitivity, not structural design.')+num('contingency','Contingency allowance',0,40,1,'%')+num('tax','Tax allowance',0,25,1,'%','Editable planning allowance; confirm applicability.')+num('pvMaint','PV inspection',0,100,1,'BHD/module/year')+num('dxMaint','DX annual service',0,1000,5,'BHD/unit/year')+num('invMaint','Inverter annual service',0,500,5,'BHD/unit/year')+num('cleaning','Cleaning per module',0,20,.5,'BHD/visit')+num('visits','Cleaning visits',0,52,1,'per year')+num('years','Study horizon',1,30,1,'years')+num('discount','Real discount rate',0,15,.5,'%');
  $('#source-list').innerHTML=D.sources.map((x,i)=>`<div class="source-item">${link(x[2],String(i+1).padStart(2,'0')+' · '+x[0])}<p>${x[1]}</p></div>`).join('');
  $('#climate-table').innerHTML='<table><thead><tr><th>Period</th><th>Mean daily low / high</th><th>Mean RH</th></tr></thead><tbody>'+D.weather.map(w=>`<tr><td>${w.period}</td><td>${w.min} / ${w.max}°C</td><td>${w.rhMean}%</td></tr>`).join('')+'</tbody></table>';
  calculate();renderInspector();syncControls();
})();
